import React, { useState } from 'react';
import { 
  FileSpreadsheet, 
  ArrowUpRight, 
  ArrowDownRight, 
  HelpCircle,
  Clock,
  Layers
} from 'lucide-react';
import { CompanyForensicProfile } from '../types';

interface MultiYearFinancialsProps {
  company: CompanyForensicProfile;
}

export const MultiYearFinancials: React.FC<MultiYearFinancialsProps> = ({ company }) => {
  const [activeTab, setActiveTab] = useState<'income' | 'balance' | 'cashflow' | 'ratios'>('income');
  const [selectedMetric, setSelectedMetric] = useState<string | null>(null);

  const years = company.financials;

  // Metric calculation definitions
  const incomeMetrics = [
    { label: 'Total Revenue', key: 'revenue', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Top-line GAAP recognized contract revenue under ASC 606' },
    { label: 'Cost of Goods Sold (COGS)', key: 'cogs', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Direct manufacturing, server compute, or merchandise fulfillment costs' },
    { label: 'Gross Profit', key: 'grossProfit', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Gross margin buffer before operating overhead' },
    { label: 'Gross Margin %', key: 'grossMarginPct', format: (v: number) => `${v.toFixed(1)}%`, desc: 'Gross margin percentage of revenue' },
    { label: 'Research & Development (R&D)', key: 'rAndD', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Direct software and technology engineering expenditures' },
    { label: 'SG&A Expenses', key: 'sga', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Sales commissions, marketing acquisition, and general administrative overhead' },
    { label: 'Operating Income (EBIT)', key: 'operatingIncome', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Core GAAP operational profitability' },
    { label: 'Operating Margin %', key: 'operatingMarginPct', format: (v: number) => `${v.toFixed(1)}%`, desc: 'EBIT margin percentage' },
    { label: 'GAAP Net Income', key: 'netIncome', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Bottom-line net earnings attributable to common shareholders' }
  ];

  const balanceMetrics = [
    { label: 'Cash & Cash Equivalents', key: 'cashAndEquivalents', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Liquid treasury bills and institutional commercial paper' },
    { label: 'Accounts Receivable (A/R)', key: 'accountsReceivable', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Audited trade customer receivables awaiting settlement' },
    { label: 'Inventory (Gross / Net)', key: 'inventory', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Finished goods, work in progress, and components at lower of cost or NRV' },
    { label: 'Total Current Assets', key: 'totalCurrentAssets', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Liquid assets maturing within 12 operating months' },
    { label: 'Total Assets', key: 'totalAssets', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Combined book value of enterprise physical and intangible assets' },
    { label: 'Current Liabilities', key: 'currentLiabilities', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Accounts payable, customer deposits, and short-term debt' },
    { label: 'Long-Term Funded Debt', key: 'longTermDebt', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Senior notes and long-term credit facility obligations' },
    { label: 'Total Liabilities', key: 'totalLiabilities', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'All claims against corporate assets' },
    { label: 'Stockholders Equity', key: 'stockholdersEquity', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Net book value attributable to equity owners' }
  ];

  const cashFlowMetrics = [
    { label: 'Operating Cash Flow (OCF)', key: 'operatingCashFlow', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Actual cash generated by core operations — Ground Truth benchmark' },
    { label: 'Capital Expenditures (CapEx)', key: 'capex', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Cash paid for property, fab equipment, and datacenter hardware' },
    { label: 'Free Cash Flow (FCF)', key: 'freeCashFlow', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'OCF minus CapEx available for buybacks, debt retirement, and M&A' },
    { label: 'Cash Conversion Ratio', key: 'operatingCashFlow', format: (v: number, row: any) => `${((row.operatingCashFlow / (row.netIncome || 1)) * 100).toFixed(0)}%`, desc: 'Ratio of OCF to Net Income. < 80% signals aggressive revenue accruals' }
  ];

  const ratioMetrics = [
    { label: 'Days Sales Outstanding (DSO)', key: 'dso', format: (v: number) => `${v.toFixed(1)} days`, desc: 'Average time to collect receivables. Surge > 15 days flags channel stuffing' },
    { label: 'Days Inventory Outstanding (DIO)', key: 'dio', format: (v: number) => `${v.toFixed(1)} days`, desc: 'Inventory turnover velocity. Rising DIO signals obsolete inventory accumulation' },
    { label: 'Sloan Balance Sheet Accrual Ratio', key: 'accrualRatio', format: (v: number) => `${(v * 100).toFixed(2)}%`, desc: '(Net Income - OCF) / Total Assets. Values > 10% indicate high manipulation risk' },
    { label: 'Asset Turnover', key: 'revenue', format: (v: number, row: any) => `${(row.revenue / row.totalAssets).toFixed(2)}x`, desc: 'Revenue generated per dollar of total balance sheet assets' }
  ];

  const activeMetrics = 
    activeTab === 'income' ? incomeMetrics :
    activeTab === 'balance' ? balanceMetrics :
    activeTab === 'cashflow' ? cashFlowMetrics : ratioMetrics;

  return (
    <div className="bg-[#0F131C] border border-[#22293d] p-4 mb-4 shadow-lg">
      {/* Top Header and Tabs */}
      <div className="flex flex-wrap items-center justify-between gap-3 pb-3 border-b border-[#1c2233]">
        <div className="flex items-center gap-2">
          <FileSpreadsheet className="h-4 w-4 text-[#FF4D4D]" />
          <div>
            <h3 className="text-xs font-mono font-bold text-white tracking-wider uppercase">
              Multi-Year & TTM Audited Financial Engine (FY22 – FY26 + TTM)
            </h3>
            <p className="text-[11px] font-mono text-[#718096]">
              SEC EDGAR XBRL Ground Truth vs Yahoo Finance TTM Trailing Twelve Months
            </p>
          </div>
        </div>

        {/* Statement Switcher Tabs */}
        <div className="flex items-center bg-[#080b10] border border-[#1f2638] p-0.5 font-mono text-xs">
          <button
            onClick={() => setActiveTab('income')}
            className={`px-3 py-1 text-[11px] ${
              activeTab === 'income' ? 'bg-[#FF4D4D] text-white font-bold' : 'text-[#8a94a6] hover:text-white'
            }`}
          >
            INCOME STATEMENT
          </button>
          <button
            onClick={() => setActiveTab('balance')}
            className={`px-3 py-1 text-[11px] ${
              activeTab === 'balance' ? 'bg-[#FF4D4D] text-white font-bold' : 'text-[#8a94a6] hover:text-white'
            }`}
          >
            BALANCE SHEET
          </button>
          <button
            onClick={() => setActiveTab('cashflow')}
            className={`px-3 py-1 text-[11px] ${
              activeTab === 'cashflow' ? 'bg-[#FF4D4D] text-white font-bold' : 'text-[#8a94a6] hover:text-white'
            }`}
          >
            CASH FLOW
          </button>
          <button
            onClick={() => setActiveTab('ratios')}
            className={`px-3 py-1 text-[11px] ${
              activeTab === 'ratios' ? 'bg-[#FF4D4D] text-white font-bold' : 'text-[#8a94a6] hover:text-white'
            }`}
          >
            FORENSIC RATIOS
          </button>
        </div>
      </div>

      {/* Financial Statement Grid Table */}
      <div className="overflow-x-auto mt-3">
        <table className="w-full text-left font-mono text-xs border-collapse">
          <thead>
            <tr className="border-b border-[#22293d] bg-[#090c12] text-[#8a94a6] text-[11px]">
              <th className="py-2.5 px-3">FINANCIAL LINE ITEM (USD)</th>
              {years.map((y) => (
                <th key={y.year} className="py-2.5 px-3 text-right">
                  <span className={y.year === 'TTM' ? 'text-[#FF4D4D] font-bold underline' : 'text-[#e1e2ea]'}>
                    {y.year}
                  </span>
                </th>
              ))}
              <th className="py-2.5 px-3 text-right text-[#a5b4fc]">5Y CAGR / TTM VAR</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#181f2f]">
            {activeMetrics.map((metric, idx) => {
              const fy22Val = (years[0] as unknown as Record<string, number>)[metric.key];
              const ttmVal = (years[years.length - 1] as unknown as Record<string, number>)[metric.key];
              const isGrowthPositive = ttmVal >= fy22Val;

              return (
                <tr
                  key={metric.label}
                  onClick={() => setSelectedMetric(selectedMetric === metric.label ? null : metric.label)}
                  className={`hover:bg-[#151c2b] transition-colors cursor-pointer ${
                    selectedMetric === metric.label ? 'bg-[#182133]' : idx % 2 === 0 ? 'bg-[#0b0e15]' : 'bg-[#0f131c]'
                  }`}
                >
                  <td className="py-2 px-3 text-[#d1d5db] font-medium flex items-center gap-1.5">
                    <span>{metric.label}</span>
                    <HelpCircle className="h-3 w-3 text-[#525f7a]" />
                  </td>

                  {years.map((y) => {
                    const rawVal = (y as unknown as Record<string, number>)[metric.key];
                    const formatted = metric.format(rawVal, y);
                    return (
                      <td key={y.year} className="py-2 px-3 text-right text-[#cbd5e1]">
                        {formatted}
                      </td>
                    );
                  })}

                  <td className="py-2 px-3 text-right">
                    <span className={`inline-flex items-center gap-0.5 text-[11px] font-bold ${
                      isGrowthPositive ? 'text-[#38A169]' : 'text-[#FF4D4D]'
                    }`}>
                      {isGrowthPositive ? <ArrowUpRight className="h-3 w-3" /> : <ArrowDownRight className="h-3 w-3" />}
                      {Math.abs(Math.round(((ttmVal - fy22Val) / (Math.abs(fy22Val) || 1)) * 100))}%
                    </span>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* Explanatory Info Box for Selected Metric */}
      {selectedMetric && (
        <div className="mt-3 p-3 bg-[#080b10] border-l-2 border-[#FF4D4D] text-xs font-mono text-[#cbd5e1] flex items-start gap-2">
          <Layers className="h-4 w-4 text-[#FF4D4D] mt-0.5 flex-shrink-0" />
          <div>
            <span className="font-bold text-white mr-2">{selectedMetric}:</span>
            <span>{activeMetrics.find((m) => m.label === selectedMetric)?.desc}</span>
            <div className="mt-1 text-[10px] text-[#718096]">
              SEC XBRL Standard Mapping: <span className="text-[#a5b4fc]">us-gaap:{selectedMetric.replace(/\s+/g, '')}</span> • Priority: P1 Audited 10-K & P3 Yahoo TTM
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
