import React, { useState } from 'react';
import { 
  FileSpreadsheet, 
  ArrowUpRight, 
  ArrowDownRight, 
  Info,
  TrendingUp,
  Table
} from 'lucide-react';
import { CompanyForensicProfile } from '../types';

interface MultiYearFinancialsProps {
  company: CompanyForensicProfile;
}

export const MultiYearFinancials: React.FC<MultiYearFinancialsProps> = ({ company }) => {
  const [activeTab, setActiveTab] = useState<'income' | 'balance' | 'cashflow' | 'ratios'>('income');
  const [selectedMetric, setSelectedMetric] = useState<string | null>(null);

  const years = company.financials;

  const incomeMetrics = [
    { label: 'Total Revenue', key: 'revenue', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Top-line GAAP recognized contract revenue under ASC 606' },
    { label: 'Cost of Goods Sold (COGS)', key: 'cogs', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Direct manufacturing, server compute, or merchandise fulfillment costs' },
    { label: 'Gross Profit', key: 'grossProfit', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Gross margin buffer before operating overhead' },
    { label: 'Gross Margin %', key: 'grossMarginPct', format: (v: number) => `${v.toFixed(1)}%`, desc: 'Gross margin percentage of revenue' },
    { label: 'Research & Development (R&D)', key: 'rAndD', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Direct software and technology engineering expenditures' },
    { label: 'SG&A Expenses', key: 'sga', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Sales commissions, marketing acquisition, and general administrative overhead' },
    { label: 'Operating Income (EBIT)', key: 'operatingIncome', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Core GAAP operational profitability' },
    { label: 'Operating Margin %', key: 'operatingMarginPct', format: (v: number) => `${v.toFixed(1)}%`, desc: 'EBIT margin percentage' },
    { label: 'GAAP Net Income', key: 'netIncome', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Bottom-line net earnings attributable to common shareholders' }
  ];

  const balanceMetrics = [
    { label: 'Cash & Cash Equivalents', key: 'cashAndEquivalents', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Liquid treasury bills and institutional commercial paper' },
    { label: 'Accounts Receivable (A/R)', key: 'accountsReceivable', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Audited trade customer receivables awaiting settlement' },
    { label: 'Inventory (Gross / Net)', key: 'inventory', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Finished goods, work in progress, and components at lower of cost or NRV' },
    { label: 'Total Current Assets', key: 'totalCurrentAssets', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Liquid assets maturing within 12 operating months' },
    { label: 'Total Assets', key: 'totalAssets', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Combined book value of enterprise physical and intangible assets' },
    { label: 'Current Liabilities', key: 'currentLiabilities', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Accounts payable, customer deposits, and short-term debt' },
    { label: 'Long-Term Funded Debt', key: 'longTermDebt', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Senior notes and long-term credit facility obligations' },
    { label: 'Total Liabilities', key: 'totalLiabilities', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'All claims against corporate assets' },
    { label: 'Stockholders Equity', key: 'stockholdersEquity', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Net book value attributable to equity owners' }
  ];

  const cashFlowMetrics = [
    { label: 'Operating Cash Flow (OCF)', key: 'operatingCashFlow', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Actual cash generated by core operations — Ground Truth benchmark' },
    { label: 'Capital Expenditures (CapEx)', key: 'capex', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'Cash paid for property, fab equipment, and datacenter hardware' },
    { label: 'Free Cash Flow (FCF)', key: 'freeCashFlow', format: (v: number) => `$${v.toLocaleString()}M`, desc: 'OCF minus CapEx available for buybacks, debt retirement, and M&A' },
    { label: 'Cash Conversion Ratio', key: 'operatingCashFlow', format: (v: number, row: any) => `${((row.operatingCashFlow / (row.netIncome || 1)) * 100).toFixed(0)}%`, desc: 'Ratio of OCF to Net Income. < 80% signals aggressive revenue accruals' }
  ];

  const ratioMetrics = [
    { label: 'Days Sales Outstanding (DSO)', key: 'dso', format: (v: number) => `${v.toFixed(1)} days`, desc: 'Average time to collect receivables. Surge > 15 days flags channel stuffing' },
    { label: 'Days Inventory Outstanding (DIO)', key: 'dio', format: (v: number) => `${v.toFixed(1)} days`, desc: 'Inventory turnover velocity. Rising DIO signals obsolete inventory accumulation' },
    { label: 'Sloan Balance Sheet Accrual Ratio', key: 'accrualRatio', format: (v: number) => `${(v * 100).toFixed(2)}%`, desc: '(Net Income - OCF) / Total Assets. Values > 10% indicate high manipulation risk' },
    { label: 'Asset Turnover', key: 'revenue', format: (v: number, row: any) => `${(row.revenue / row.totalAssets).toFixed(2)}x`, desc: 'Revenue generated per dollar of total balance sheet assets' }
  ];

  const activeMetrics = 
    activeTab === 'income' ? incomeMetrics :
    activeTab === 'balance' ? balanceMetrics :
    activeTab === 'cashflow' ? cashFlowMetrics : ratioMetrics;

  return (
    <div className="bg-slate-900 border border-slate-800 p-5 rounded-xl shadow-sm space-y-4">
      {/* Top Header and Tabs */}
      <div className="flex flex-wrap items-center justify-between gap-3 pb-3 border-b border-slate-800">
        <div className="flex items-center gap-2.5">
          <FileSpreadsheet className="h-5 w-5 text-emerald-400" />
          <div>
            <h3 className="text-sm font-semibold text-white">
              Multi-Year Audited Financial Statements
            </h3>
            <p className="text-xs text-slate-400 mt-0.5">
              Historical comparisons across audited FY22–FY26 Form 10-Ks and TTM trailing reports
            </p>
          </div>
        </div>

        {/* Statement Switcher Tabs */}
        <div className="flex items-center bg-slate-950/60 border border-slate-800 p-1 rounded-lg text-xs font-medium">
          <button
            onClick={() => setActiveTab('income')}
            className={`px-3 py-1.5 rounded-md transition-all ${
              activeTab === 'income' ? 'bg-red-500 text-white shadow-sm' : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            Income Statement
          </button>
          <button
            onClick={() => setActiveTab('balance')}
            className={`px-3 py-1.5 rounded-md transition-all ${
              activeTab === 'balance' ? 'bg-red-500 text-white shadow-sm' : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            Balance Sheet
          </button>
          <button
            onClick={() => setActiveTab('cashflow')}
            className={`px-3 py-1.5 rounded-md transition-all ${
              activeTab === 'cashflow' ? 'bg-red-500 text-white shadow-sm' : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            Cash Flow
          </button>
          <button
            onClick={() => setActiveTab('ratios')}
            className={`px-3 py-1.5 rounded-md transition-all ${
              activeTab === 'ratios' ? 'bg-red-500 text-white shadow-sm' : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            Ratios &amp; Working Capital
          </button>
        </div>
      </div>

      {/* Financial Statement Grid Table */}
      <div className="overflow-x-auto rounded-lg border border-slate-800">
        <table className="w-full text-left text-xs border-collapse">
          <thead>
            <tr className="border-b border-slate-800 bg-slate-950/80 text-slate-400 font-medium text-[11px]">
              <th className="py-2.5 px-3">Financial Line Item (USD)</th>
              {years.map((y) => (
                <th key={y.year} className="py-2.5 px-3 text-right">
                  <span className={y.year === 'TTM' ? 'text-red-400 font-semibold underline' : 'text-slate-300'}>
                    {y.year}
                  </span>
                </th>
              ))}
              <th className="py-2.5 px-3 text-right text-slate-400">5Y Trend / Variance</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-800/60">
            {activeMetrics.map((metric, idx) => {
              const fy22Val = (years[0] as unknown as Record<string, number>)[metric.key];
              const ttmVal = (years[years.length - 1] as unknown as Record<string, number>)[metric.key];
              const isGrowthPositive = ttmVal >= fy22Val;

              return (
                <tr
                  key={metric.label}
                  onClick={() => setSelectedMetric(selectedMetric === metric.label ? null : metric.label)}
                  className={`hover:bg-slate-800/40 transition-colors cursor-pointer ${
                    selectedMetric === metric.label ? 'bg-slate-800/60' : idx % 2 === 0 ? 'bg-slate-900/40' : 'bg-slate-900'
                  }`}
                >
                  <td className="py-2.5 px-3 text-slate-200 font-medium flex items-center gap-1.5">
                    <span>{metric.label}</span>
                    {selectedMetric === metric.label && (
                      <span className="text-[10px] text-slate-400 font-normal ml-1">
                        (Active Detail)
                      </span>
                    )}
                  </td>
                  {years.map((y) => {
                    const rawVal = (y as unknown as Record<string, number>)[metric.key];
                    const formatted = metric.format(rawVal, y);
                    return (
                      <td
                        key={y.year}
                        className={`py-2.5 px-3 text-right font-mono ${
                          y.year === 'TTM' ? 'text-white font-semibold' : 'text-slate-300'
                        }`}
                      >
                        {formatted}
                      </td>
                    );
                  })}
                  <td className="py-2.5 px-3 text-right">
                    <span
                      className={`inline-flex items-center gap-1 text-[11px] font-medium ${
                        isGrowthPositive ? 'text-emerald-400' : 'text-red-400'
                      }`}
                    >
                      {isGrowthPositive ? <ArrowUpRight className="h-3 w-3" /> : <ArrowDownRight className="h-3 w-3" />}
                      {fy22Val !== 0 ? `${(((ttmVal - fy22Val) / Math.abs(fy22Val)) * 100).toFixed(1)}%` : 'N/A'}
                    </span>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* Selected Metric Explanation Helper */}
      {selectedMetric && (
        <div className="p-3 bg-slate-950/60 border border-slate-800 rounded-lg text-xs flex items-start gap-2 animate-fadeIn">
          <Info className="h-4 w-4 text-slate-400 mt-0.5 shrink-0" />
          <div>
            <strong className="text-white font-medium">{selectedMetric}:</strong>{' '}
            <span className="text-slate-300">
              {activeMetrics.find((m) => m.label === selectedMetric)?.desc}
            </span>
          </div>
        </div>
      )}
    </div>
  );
};
